image: anapsix/alpine-java:8_jdk

before_script:
  - which java
  - which javac

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - ./gradlew setupCiWorkspace
    - ./gradlew ciWriteBuildNumber
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 month

production:
  stage: deploy
  script: ./gradlew curseforge && ./gradlew bintrayUpload
  when: on_success
  only:
    refs:
      - tags
